# Generated by Django 4.2.16 on 2024-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_recommendationlog_recommended_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='recommended_allocation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
