# Generated by Django 4.2.16 on 2024-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_recommendationlog_recommended_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='current_investment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='recommended_volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_investment',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
    ]
