# Generated by Django 4.2.16 on 2024-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchindex',
            name='sector',
        ),
        migrations.AddField(
            model_name='searchindex',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
